

select * from customer_shopping_data_cleaned;

describe customer_shopping_data_cleaned;

-- Count the number of unique customers in the dataset
select count(distinct customer_id)
from customer_shopping_data_cleaned;

select *
from customer_shopping_data_cleaned
order by quantity desc
    limit 20;

select *
from customer_shopping_data_cleaned
order by price desc
    limit 20;

--  Determine the time period covered by the dataset.
select
    min(invoice_date) as min_date,
    max(invoice_date) as max_date
from customer_shopping_data_cleaned;
-- 2021-01-01,2023-03-08

--  Data summary: total rows, unique customers, unique transactions, and unique product categories.
select
    count(*) as total_rows,
    count(distinct customer_id) as unique_customers,
    count(distinct invoice_no) as unique_invoices,
    count(distinct category) as unique_categories
from customer_shopping_data_cleaned;
-- total_rows,unique_customers,unique_invoices,unique_categories
-- 99457,          99457,           99457,           8

--  Compare the average item price by gender
select
    gender,
    avg(price) as avg_price
from customer_shopping_data_cleaned
group by gender;
-- gender,avg_price
-- Female,688.137615
-- Male,690.920933

--  Calculate total revenue across the entire dataset
select
    sum(price) as total_revenue
from customer_shopping_data_cleaned;
-- total_revenue
-- 68551365.91

-- revenue by year and total revenue across the entire dataset
SELECT
    YEAR(invoice_date) AS year,
    ROUND(SUM(price), 2) AS revenue
FROM customer_shopping_data_cleaned
WHERE invoice_date BETWEEN '2021-01-01' AND '2023-03-08'
GROUP BY YEAR(invoice_date)

UNION ALL

SELECT
    'TOTAL' AS year,
    ROUND(SUM(price), 2) AS revenue
FROM customer_shopping_data_cleaned
WHERE invoice_date BETWEEN '2021-01-01' AND '2023-03-08';
-- year,revenue
-- 2022,31372826.18
-- 2021,31316304.63
-- 2023,5862235.10
-- TOTAL,68551365.91

-- Calculate the total number of unique transactions for each year
-- and for the entire dataset period.

SELECT
    year,
    COUNT(DISTINCT invoice_no) AS transactions
FROM (
         SELECT
             YEAR(invoice_date) AS year,
             invoice_no
         FROM customer_shopping_data_cleaned
         WHERE invoice_date BETWEEN '2021-01-01' AND '2023-03-08'
     ) AS t
GROUP BY year

UNION ALL

SELECT
    'TOTAL' AS year,
    COUNT(DISTINCT invoice_no) AS transactions
FROM customer_shopping_data_cleaned
WHERE invoice_date BETWEEN '2021-01-01' AND '2023-03-08';

-- year,transactions
-- 2021,45382
-- 2022,45551
-- 2023,8524
-- TOTAL,99457

SELECT
    shopping_mall,
    COUNT(DISTINCT invoice_no) AS transactions
FROM customer_shopping_data_cleaned
WHERE YEAR(invoice_date) = 2021
GROUP BY shopping_mall
ORDER BY transactions DESC;
-- shopping_mall,transactions
-- Mall of Istanbul,9026
-- Kanyon,8946
-- Metrocity,6856
-- Metropol AVM,4679
-- Istinye Park,4419
-- Cevahir AVM,2365
-- Zorlu Center,2330
-- Viaport Outlet,2286
-- Forum Istanbul,2253
-- Emaar Square Mall,2222


SELECT
    shopping_mall,
    COUNT(DISTINCT invoice_no) AS transactions
FROM customer_shopping_data_cleaned
WHERE YEAR(invoice_date) = 2022
GROUP BY shopping_mall
ORDER BY transactions DESC;
-- shopping_mall,transactions
-- Mall of Istanbul,9202
-- Kanyon,9153
-- Metrocity,6890
-- Metropol AVM,4613
-- Istinye Park,4521
-- Forum Istanbul,2281
-- Zorlu Center,2281
-- Cevahir AVM,2231
-- Viaport Outlet,2220
-- Emaar Square Mall,2159

--  Compare total revenue generated by each shopping mall
select
    shopping_mall,
    sum(price) as revenue_by_mall
from customer_shopping_data_cleaned
group by shopping_mall
order by revenue_by_mall desc;
-- shopping_mall,revenue_by_mall
-- Mall of Istanbul,13851737.62
-- Kanyon,13710755.24
-- Metrocity,10249980.07
-- Metropol AVM,6937992.99
-- Istinye Park,6717077.54
-- Zorlu Center,3509649.02
-- Cevahir AVM,3433671.84
-- Viaport Outlet,3414019.46
-- Emaar Square Mall,3390408.31
-- Forum Istanbul,3336073.82


-- Compare revenue across product categories
select
    category,
    sum(price) as revenue
from customer_shopping_data_cleaned
group by category
order by revenue desc;

-- category,revenue
-- Clothing,31075684.64
-- Shoes,18135336.89
-- Technology,15772050.00
-- Cosmetics,1848606.90
-- Toys,1086704.64
-- Food & Beverage,231568.71
-- Books,226977.30
-- Souvenir,174436.83


-- Compare revenue generated by each payment method
select payment_method,
       sum(price) as revenue_by_payment_method
from customer_shopping_data_cleaned
group by payment_method
order by revenue_by_payment_method desc;

-- Compare total revenue generated by male and female customers
select
    gender,
    sum(price) as revenue
from customer_shopping_data_cleaned
group by gender;

-- Compare the number of unique transactions by gender
SELECT
    gender,
    COUNT(DISTINCT invoice_no) AS total_transactions
FROM customer_shopping_data_cleaned
GROUP BY gender;

-- Compare average spending per transaction by gender
select
    gender,
    round(avg(price),2) as avg_spend_per_transactiom
from customer_shopping_data_cleaned
group by gender;

--  Analyze purchase volume by gender and product category
select
    gender,
    category,
    count(*) as total_purchases
from customer_shopping_data_cleaned
group by gender, category
order by gender, total_purchases desc;

-- Analyze purchase volume by gender, age group, and category
select
    gender,
    case
        when age between 18 and 25 then '18-25'
        when age between 26 and 35 then '26-35'
        when age between 36 and 45 then '36-45'
        when age between 46 and 60 then '46-60'
        else '60+'
        end as age_group,
    category,
    count(*) as total_purchases_by_age_group
from customer_shopping_data_cleaned
group by
    gender,
    age_group,
    category
order by
    gender,
    age_group,
    total_purchases_by_age_group desc;

-- Compare revenue and average spend across gender, age group, and category
select
    gender,
    case
        when age between 18 and 25 then '18-25'
        when age between 26 and 35 then '26-35'
        when age between 36 and 45 then '36-45'
        when age between 46 and 60 then '46-60'
        else '60+'
        end as age_group,
    category,
    round(sum(price),2) as revenue,
    round(avg(price),2) as avg_order_value
from customer_shopping_data_cleaned
group by
    gender,
    age_group,
    category
order by revenue desc;

-- Examine how average spending varies across individual customer ages
select
    age,
    round(avg(price),2) as avg_spend
from customer_shopping_data_cleaned
group by age
order by age;

--  Compare total revenue between 2021 and 2022
select
    year(invoice_date) as year,
    sum(price) as revenue_by_year
from customer_shopping_data_cleaned
group by year
order by year;

-- Analyze monthly revenue trends across the two years
select
    year(invoice_date) as year,
    month(invoice_date) as month,
    round(sum(price),2) as revenue_by_month
from customer_shopping_data_cleaned
group by year, month
order by year, month;

-- Compare the number of unique transactions by month and year
SELECT
    YEAR(invoice_date) AS year,
    MONTH(invoice_date) AS month,
    COUNT(DISTINCT invoice_no) AS transactions
FROM customer_shopping_data_cleaned
GROUP BY
    YEAR(invoice_date),
    MONTH(invoice_date)
ORDER BY
    year,
    month;

-- Compare the number of purchases across product categories
select
    category,
    count(*) as total_sales
from customer_shopping_data_cleaned
group by category
order by total_sales desc;

-- Compare average item/order value across product categories
select
    category,
    round(avg(price),2) as avg_order_value
from customer_shopping_data_cleaned
group by category
order by avg_order_value desc;

-- Analyze revenue by the combination of shopping mall and product category
select
    shopping_mall,
    category,
    round(sum(price),2) as revenue
from customer_shopping_data_cleaned
group by shopping_mall, category
order by shopping_mall, revenue desc;

-- Compare the number of unique transactions handled by each shopping mall
SELECT
    shopping_mall,
    COUNT(DISTINCT invoice_no) AS transactions
FROM customer_shopping_data_cleaned
GROUP BY shopping_mall
ORDER BY transactions DESC;

-- Compare average transaction value across shopping malls
select
    shopping_mall,
    avg(price) as avg_transaction
from customer_shopping_data_cleaned
group by shopping_mall
order by avg_transaction desc;

--  Calculate the size of each shopping basket and examine the distribution
--  of basket sizes across shopping malls
select
    shopping_mall,
    basket_size,
    count(*) as number_of_baskets
from (
         select
             shopping_mall,
             invoice_no,
             sum(quantity) as basket_size
         from customer_shopping_data_cleaned
         group by shopping_mall, invoice_no
     ) t
group by shopping_mall, basket_size
order by shopping_mall, basket_size;

-- Create a reusable basket-level dataset containing basket size and value
-- for each transaction at each shopping mall
create view basket_level as
select
    shopping_mall,
    invoice_no,
    sum(quantity) as basket_size,
    sum(price) as basket_value
from customer_shopping_data_cleaned
group by shopping_mall, invoice_no;


--  Compare category revenue between 2021 and 2022 to identify
--  which categories gained or lost revenue year over year
WITH yearly_revenue AS (
    SELECT
        category,
    YEAR(invoice_date) AS year,
    SUM(price) AS revenue
FROM customer_shopping_data_cleaned
WHERE YEAR(invoice_date) IN (2021, 2022)
GROUP BY category, YEAR(invoice_date)
    ),

    pivoted AS (
SELECT
    category,
    SUM(CASE WHEN year = 2022 THEN revenue ELSE 0 END) AS revenue_2022,
    SUM(CASE WHEN year = 2021 THEN revenue ELSE 0 END) AS revenue_2021
FROM yearly_revenue
GROUP BY category
    )

SELECT
    category,
    ROUND(revenue_2022 - revenue_2021, 2) AS revenue_change
FROM pivoted
ORDER BY revenue_change ASC;


-- Compare the number of unique transactions at each shopping mall
-- between 2021 and 2022
SELECT
    YEAR(invoice_date) AS year,
    shopping_mall,
    COUNT(DISTINCT invoice_no) AS transactions
FROM customer_shopping_data_cleaned
WHERE YEAR(invoice_date) IN (2021, 2022)
GROUP BY
    YEAR(invoice_date),
    shopping_mall
ORDER BY
    year,
    transactions DESC;

-- Compare total unique transactions between 2021 and 2022
SELECT
    YEAR(invoice_date) AS year,
    COUNT(DISTINCT invoice_no) AS total_transactions
FROM customer_shopping_data_cleaned
WHERE YEAR(invoice_date) IN (2021, 2022)
GROUP BY YEAR(invoice_date)
ORDER BY year;

-- Check whether any records have a missing or blank shopping mall.
SELECT
    COUNT(*) AS rows_without_mall
FROM customer_shopping_data_cleaned
WHERE shopping_mall IS NULL
   OR TRIM(shopping_mall) = '';

-- Count unique transactions for each shopping mall and year
-- using the same transaction definition as the overall total.
SELECT
    YEAR(invoice_date) AS year,
    shopping_mall,
    COUNT(DISTINCT invoice_no) AS transactions
FROM customer_shopping_data_cleaned
WHERE YEAR(invoice_date) IN (2021, 2022)
GROUP BY
    YEAR(invoice_date),
    shopping_mall
ORDER BY
    year,
    transactions DESC;

-- Check for inconsistent shopping mall names that could split
-- the same mall into multiple categories.
SELECT
    shopping_mall,
    LENGTH(shopping_mall) AS name_length
FROM customer_shopping_data_cleaned
GROUP BY shopping_mall, LENGTH(shopping_mall)
ORDER BY shopping_mall;